export const Blockchain = [
    {
        name:"Ethereum",
        networks:[
            {
                name:"mainnet",
                id:1
            },
            {
                name:"goerli",
                Id:5
            },
            {
                name:"Sepolia",
                Id:11155111
            }
        ]
    },
    {
        name:"Polygon",
        networks:[
            {
                name:"mainnet",
                id:137
            },
            {
                name: "mumbai",
                Id:80001
            }
        ]
    },
    {
        name:"Binance",
        networks:[
            {
                name:"mainnet",
                id:56
            },
            {
                name:"BNB testnet",
                id:97
            }
        ]
    }
]