export const Blockchain = [
    {
        name:"Ethereum",
        networks:[
            {
                name:"mainnet",
                id:1
            },
            {
                name:"goerli",
                Id:5
            },
            {
                name:"Sepolia",
                Id:11155111
            }
        ]
    },
    {
        name:"Polygon",
        networks:[]
    },
    {
        name:"Binance",
        networks:[]
    }
]